### PR TITLE
Initial MK4 support. Handle command detection

### PR DESCRIPTION
**Pull request by jukebox42**
# I CANNOT STRESS THIS ENOUGH, DO NOT TRY THIS BRANCH IT'S NOT READY FOR USERS.

TODO:
- [x] multi print command detection
- [ ] Single print dialog support
- [ ] Single print command detection
- [x] Better error code handling
- [x] Extra commands (cut, eject)
- [x] Testing

This Branch aims to introduce support for the MK3.5/3.9/4 with an MMU.

Background:
When Prusa Updated the MMU for the MK4 they no longer send over the serial commands for the MMU. This means the information we had available is slimmer. On the flip, it's far less noisy in your input logs.

Single print mode is more difficult with the MK3.5+. Because there's no "MMU Single" profile, the sliced files don't contain a `Tx` command. This is what we use to pause the print, show the selection, and then insert before the M109 (wait for extruder) for the MK3.

Here's what I plan to try:

For the MK3:
- Look for `Tx` (tool change promp). 
- Remove it
- Show the prompt
- Wait for `M109 S` (wait for heater)
- Inject a tool command 

For the MK3.5:
- Look for `M104 S` (heat nozzle start). 
- DO NOT remove it
- Show the prompt
- Wait for `M109 S` (wait for heater)
- Inject a tool command AND the mmu follow up commands I stole from a multi slice

For the MK3.9/4:
- Look for `M104 S` (heat nozzle start). 
- DO NOT remove it
- Show the prompt
- Wait for `M569 S0 E` (set extruder speed)
- Inject a tool command AND the mmu follow up commands I stole from a multi slice

### CODE REVIEW

**Comment by Tor-Einar** [comment]
Your plugin was for me the most used on my Mk3s and MMU2. Very happy that you are developing this for the Mk4/mmu3 :)

**Comment by Vttran918** [comment]
Looking forward to support on the mk4. Do you have any updates on if some of the things you tried worked?

**Comment by TangoOversway** [comment]
I have a Mk3.5 and an MMU3 that I just installed. If I can help with testing, let me know.

**Comment by jukebox42** [comment]
Hey All, I'm going to merge and get this released. It doesn't fix the single print mode yet. I'll start a new PR for that. But it does fix mmu detection so I think it's worth getting that out.

Prusa getting rid of the single print mode for MMU makes this tricky. There doesn't seem to be a reliable way to catch if a print is a single print anymore. I hope they bring it back. I have an idea that should hopefully fill the void while we wait. Thanks for the patience.

**Pull request merged**
